{% set name = "vocalpy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vocalpy-{{ version }}.tar.gz
  sha256: 4071546c1e74b7e40592d63733b78a56b9a8e1d4b436459229d98e80b5625eff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - attrs >=23.1.0
    - crowsetta >=5.0.0
    - dask-core >=2.10.1
    - evfuncs >=0.3.3
    - librosa >=0.10.0.post2
    - matplotlib-base >=3.7.1
    - numpy >=1.21.0
    - pandas >=1.3.5
    - scipy >=1.7.0
    - pysoundfile >=0.12.1
    - sqlalchemy >=2.0.12

test:
  imports:
    - vocalpy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A core package for acoustic communication research in Python
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://vocalpy.readthedocs.io/en/latest/
  dev_url: https://github.com/vocalpy/vocalpy

extra:
  recipe-maintainers:
    - NickleDave
