{% set name = "vocalpy" %}
{% set version = "0.10.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vocalpy-{{ version }}.tar.gz
  sha256: 09d3317188e5f07c7fd3dadc1d01756efdf82fba919adbb769a2ae39e59c6bcf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.10
    - attrs >=23.1.0
    - crowsetta >=5.1.0
    - dask-core >=2.10.1
    - h5netcdf >=1.3.0
    - librosa >=0.10.0.post2
    - matplotlib-base >=3.7.1
    - numpy >=1.24.0
    - pandas >=1.4.0
    - pooch >=1.8.1
    - scipy >=1.9.0
    - pysoundfile >=0.12.1
    - xarray >=2023.11.0

test:
  imports:
    - vocalpy
  commands:
    - pip check
  requires:
    # place temporary upper bound on pip so pip check does not fail on soundfile
    # see https://github.com/conda-forge/pysoundfile-feedstock/issues/22
    - pip <24.2

about:
  summary: A core package for acoustic communication research in Python
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://vocalpy.readthedocs.io/en/latest/
  dev_url: https://github.com/vocalpy/vocalpy

extra:
  recipe-maintainers:
    - NickleDave
