{% set python_min = "3.12" %}
{% set name = "vocalpy" %}
{% set version = "0.10.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vocalpy-{{ version }}.tar.gz
  sha256: 4bb3bd88cb94fe8a551ccac844b436615070cac2b96b40f3f963a7419e3db038

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=25.3.0
    - crowsetta >=5.1.3
    - dask-core >=2025.5.1
    - h5netcdf >=1.3.0
    - librosa >=0.11.0
    - matplotlib-base >=3.9.0
    - numpy >=2.0.0
    - pandas >=2.2.0
    - pooch >=1.8.2
    - scipy >=1.12.0
    - pysoundfile >=0.13.1
    - xarray >=2023.11.0

test:
  imports:
    - vocalpy
  commands:
    - pip check
  requires:
    # place temporary upper bound on pip so pip check does not fail on soundfile
    # see https://github.com/conda-forge/pysoundfile-feedstock/issues/22
    - pip <24.2
    - python {{ python_min }}

about:
  summary: A core package for acoustic communication research in Python
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://vocalpy.readthedocs.io/en/latest/
  dev_url: https://github.com/vocalpy/vocalpy

extra:
  recipe-maintainers:
    - NickleDave
