{% set name = "vocalpy" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vocalpy-{{ version }}.tar.gz
  sha256: 56e934d60f6cfa0a1620307b1f0b46309422eb510bfcbdad8782e0225c76fee2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - attrs >=23.1.0
    - crowsetta >=5.0.2
    - dask-core >=2.10.1
    - h5netcdf >=1.3.0
    - librosa >=0.10.0.post2
    - matplotlib-base >=3.7.1
    - numpy >=1.22.0
    - pandas >=1.4.0
    - pooch >=1.8.1
    - scipy >=1.7.0
    - pysoundfile >=0.12.1
    - xarray >=2023.11.0

test:
  imports:
    - vocalpy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A core package for acoustic communication research in Python
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://vocalpy.readthedocs.io/en/latest/
  dev_url: https://github.com/vocalpy/vocalpy

extra:
  recipe-maintainers:
    - NickleDave
