{% set python_min = "3.11" %}
{% set name = "vocalpy" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vocalpy-{{ version }}.tar.gz
  sha256: 006ea2d2e92c7708cd59267652f0a2b744822085f14fb18d810fe784869cc7af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=25.3.0
    - crowsetta >=5.1.1
    - dask-core >=2025.5.1
    - h5netcdf >=1.3.0
    - librosa >=0.10.2.post1
    - matplotlib-base >=3.7.1
    - numpy >=1.26.0
    - pandas >=2.1.0
    - pooch >=1.8.2
    - scipy >=1.12.0
    - pysoundfile >=0.12.1
    - xarray >=2023.11.0

test:
  imports:
    - vocalpy
  commands:
    - pip check
  requires:
    # place temporary upper bound on pip so pip check does not fail on soundfile
    # see https://github.com/conda-forge/pysoundfile-feedstock/issues/22
    - pip <24.2
    - python {{ python_min }}

about:
  summary: A core package for acoustic communication research in Python
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://vocalpy.readthedocs.io/en/latest/
  dev_url: https://github.com/vocalpy/vocalpy

extra:
  recipe-maintainers:
    - NickleDave
